name: Gestures
description: An Gestures plugin created with love.
version: '${version}'
main: com.chunkslab.gestures.GesturesPlugin
api-version: '1.17'
authors: [amownyy, ChunksLab]
website: https://chunkslab.com/
folia-supported: true
depend:
  - PlaceholderAPI
softdepend:
  - Nexo
  - Oraxen
  - ItemsAdder
  - CraftEngine