name: Gestures
description: An Gestures plugin created with love.
version: '${version}'
main: com.chunkslab.gestures.GesturesPlugin
api-version: '1.17'
authors: [amownyy, ChunksLab]
website: https://chunkslab.com/
folia-supported: true
depend:
  - PlaceholderAPI
softdepend:
  - Nexo
  - Oraxen
  - ItemsAdder
  - CraftEngine
libraries:
  - 'com.google.code.gson:gson:${gson_version}'
  - 'org.xerial:sqlite-jdbc:${sqlite_driver_version}'
  - 'com.h2database:h2:${h2_driver_version}'
  - 'org.mongodb:mongodb-driver-sync:${mongodb_driver_version}'
  - 'com.zaxxer:HikariCP:${hikari_version}'
  - 'org.mariadb.jdbc:mariadb-java-client:${mariadb_driver_version}'
  - 'com.mysql:mysql-connector-j:${mysql_driver_version}'
  - 'redis.clients:jedis:${jedis_version}'